[package]
name = "driftwave-core"
version = "0.1.0"
edition = "2024"

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[features]
default = []
wasm = []