[book]
authors = ["Lily Dayton"]
language = "en"
multilingual = false
src = "src"
title = "Driftwave"
description = "High-performance audio synthesis library for Rust"

[build]
build-dir = "book"

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/ldayton/Driftwave"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/ldayton/Driftwave/edit/main/docs/{path}"
site-url = "/Driftwave/"
cname = ""
no-section-label = false
additional-css = ["custom.css"]

[output.html.fold]
enable = true
level = 0

[output.html.playground]
runnable = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
