name: Build Linux App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libfuse2t64 \
          libnss3-dev \
          desktop-file-utils \
          zsync \
          patchelf

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Node dependencies
      run: npm ci

    - name: Build Tauri app
      run: |
        set -x
        # Make AppImage tools executable
        chmod +x ~/.cache/tauri/linuxdeploy-*.AppImage || true
        RUST_LOG=debug npm run tauri build -- -- --bin driftwave --verbose 2>&1 | tee build.log
        echo "Exit code: $?"
      env:
        RUST_LOG: debug
        RUST_BACKTRACE: full
        NO_STRIP: true
        APPIMAGE_EXTRACT_AND_RUN: 1

    - name: Upload deb artifact
      uses: actions/upload-artifact@v4
      with:
        name: driftwave-linux-deb
        path: target/release/bundle/deb/*.deb

    - name: Upload rpm artifact
      uses: actions/upload-artifact@v4
      with:
        name: driftwave-linux-rpm
        path: target/release/bundle/rpm/*.rpm

    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: driftwave-linux-appimage
        path: target/release/bundle/appimage/*.AppImage

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-log
        path: build.log
      if: always()