name: Windows Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip windows]') }}
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: examples/tauri/package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './examples/tauri/src-tauri -> target'

      - name: Install frontend dependencies
        working-directory: examples/tauri
        run: npm ci

      - name: Build Tauri app
        working-directory: examples/tauri
        shell: bash
        run: |
          set -x
          npm run tauri build -- --verbose 2>&1 | tee build.log
          echo "Exit code: $?"
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: full

      - name: Upload .exe installer
        uses: actions/upload-artifact@v4
        with:
          name: Driftwave-windows-exe
          path: examples/tauri/src-tauri/target/release/bundle/nsis/*.exe
          retention-days: 7

      - name: List build artifacts
        run: |
          echo "=== Build artifacts ==="
          dir examples\tauri\src-tauri\target\release\bundle\nsis\

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-log
          path: build.log
        if: always()