name: Linux Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip linux]') }}
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libnss3-dev

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Node dependencies
      run: npm ci

    - name: Build Tauri app
      run: |
        set -x
        RUST_LOG=debug npm run tauri build -- -- --bin driftwave --verbose 2>&1 | tee build.log
        echo "Exit code: $?"
      env:
        RUST_LOG: debug
        RUST_BACKTRACE: full
        NO_STRIP: true

    - name: Upload deb artifact
      uses: actions/upload-artifact@v4
      with:
        name: driftwave-linux-deb
        path: target/release/bundle/deb/*.deb

    - name: Upload rpm artifact
      uses: actions/upload-artifact@v4
      with:
        name: driftwave-linux-rpm
        path: target/release/bundle/rpm/*.rpm

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-log
        path: build.log
      if: always()