name: Build Windows App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Tauri app
        run: npm run tauri build -- --bin driftwave
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Upload .exe installer
        uses: actions/upload-artifact@v4
        with:
          name: Driftwave-windows-exe
          path: target/release/bundle/nsis/*.exe
          retention-days: 7

      - name: Upload .msi installer
        uses: actions/upload-artifact@v4
        with:
          name: Driftwave-windows-msi
          path: target/release/bundle/msi/*.msi
          retention-days: 7

      - name: List build artifacts
        run: |
          echo "=== Build artifacts ==="
          dir target\release\bundle\nsis\
          dir target\release\bundle\msi\