name: Web Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Node dependencies
      run: npm ci

    - name: Build WASM module
      run: |
        cd src-web
        wasm-pack build --target web --out-dir pkg
      env:
        RUST_LOG: debug

    - name: Upload WASM package
      uses: actions/upload-artifact@v4
      with:
        name: driftwave-web-wasm
        path: src-web/pkg/

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: web-build-log
        path: build.log
      if: always()